// dapi
export const UPDATE_NETWORKS = 'UPDATE_NETWORKS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DISCONNECT = 'DISCONNECT';
export const RESET = 'RESET';
export const UPDATE_STAKE_ROUND_INFO = 'UPDATE_STAKE_ROUND_INFO';
export const UPDATE_ACCOUNT_BALANCE = 'UPDATE_ACCOUNT_BALANCE';
export const UPDATE_ACCOUNT_TOTAL_STAKE = 'UPDATE_ACCOUNT_TOTAL_STAKE';
export const UPDATE_ACCOUNT_STAKE_REWARDS = 'UPDATE_ACCOUNT_STAKE_REWARDS';
export const UPDATE_ACCOUNT_UNCLAIMED = 'UPDATE_ACCOUNT_UNCLAIMED';
export const UPDATE_NODE_LIST = 'UPDATE_NODE_LIST';
export const UPDATE_ACCOUNT_STAKES = 'UPDATE_ACCOUNT_STAKES';
