// dapi
export const UPDATE_NETWORKS = 'UPDATE_NETWORKS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DISCONNECT = 'DISCONNECT';
export const RESET = 'RESET';
export const UPDATE_STAKE_ROUND_INFO = 'UPDATE_STAKE_ROUND_INFO';
